- hosts: all
  tasks:

    - community.docker.docker_network:
        name: devops-example

    - community.docker.docker_container:
        name: app
        image: "1g0rbm/devops:{{ version }}"
        restart_policy: always
        state: started
        networks:
          - name: devops-example
        env:
          NODE_ENV: production
          DATABASE_NAME: "{{ db_name }}"
          DATABASE_USERNAME: "{{ db_user }}"
          DATABASE_PASSWORD: "{{ db_password }}"
          DATABASE_PORT: "{{ db_port }}"
          DATABASE_HOST: "{{ db_host }}"

    - community.docker.docker_container:
        name: caddy
        image: "1g0rbm/devops-caddy:{{ version }}"
        restart_policy: always
        state: started
        networks:
          - name: devops-example
        ports:
          - 80:80
          - 443:443
