- hosts: all

  tasks:
    - apt:
        name: python3-pip
        update_cache: true
        cache_valid_time: 604800 # 1 week
      become: true

    - pip:
        name: docker

    - name: Create dir for postgres cert
      file:
        path: ~/.postgresql
        state: directory
    
    - name: Download postgres cert
      command: bash -c 'wget "https://storage.yandexcloud.net/cloud-certs/CA.pem" -O ~/.postgresql/root.crt'

    - name: Chmod postgres root.cert
      file:
        path: ~/.postgresql/root.crt
        state: touch
        mode: 0660

  roles:
    - { role: datadog.datadog, become: yes }
  vars:
    datadog_api_key: "be3c00ab60d231bcc3a51a95e9ec4990"
    datadog_site: "datadoghq.com"
    datadog_checks:
      process:
        init_config:
        instances:
          - name: ssh
            search_string: ['ssh', 'sshd']
          - name: syslog
            search_string: ['rsyslog']
            cpu_check_interval: 0.2
            exact_match: true
            ignore_denied_access: true
          - name: Check main page
