- hosts: all

  tasks:
    - apt:
        name: python3-pip
        update_cache: true
        cache_valid_time: 604800 # 1 week
      become: true

    - pip:
        name: docker

    - name: Create dir for postgres cert
      file:
        path: ~/.postgresql
        state: directory
    
    - name: Download postgres cert
      command: bash -c 'wget "https://storage.yandexcloud.net/cloud-certs/CA.pem" -O ~/.postgresql/root.crt'

    - name: Chmod postgres root.cert
      file:
        path: ~/.postgresql/root.crt
        state: touch
        mode: 0660
