name: release

on:
  create:
    tags:
      - v*

env:
  APP_IMAGE_NAME: 1g0rbm/devops

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - run: docker pull ${{ env.APP_IMAGE_NAME }}:latest

      - run: docker tag ${{ env.APP_IMAGE_NAME }}:latest ${{ env.APP_IMAGE_NAME }}:${{ github.ref_name }}

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - run: docker push ${{ env.APP_IMAGE_NAME }}:${{ github.ref_name }}

      - run: docker pull ${{ env.APP_IMAGE_NAME }}-caddy:latest
      - run: docker tag ${{ env.APP_IMAGE_NAME }}-caddy:latest hexletcomponents/devops-example-caddy:${{ github.ref_name }}
      - run: docker push ${{ env.APP_IMAGE_NAME }}-caddy:${{ github.ref_name }}
